### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Rtakaha** [yunfanLu/INR-Event-VSR#1]
Hi, I have checked your research and am really interested in it! Thank you for your great work :)

One quick question, is it decided when to release your code and dataset?

Thank you!

**Comment by yunfanLu** [comment]
Apologies for the delayed response. The project we are working on is sponsored by a company that mandates the open sourcing of the code and data after the defense, which is scheduled for June. We will be releasing the code and data shortly thereafter. Thank you for your interest in our work.

**Comment by Rtakaha** [comment]
Thank you very much for your response.
Okay, I will wait for your code to be released. Good luck with your defense!

**Comment by yunfanLu** [comment]
Hello, all my codes are open source. Hope to help you. If you have any questions, please leave a message in the issue. Thank you for your interest in my work.
