### ISSUE TITLE
How to download the compressed dataset

### ISSUE THREAD

**Issue by CheungBH** [yunfanLu/INR-Event-VSR#10]
Hi. Thanks for your great work.
I am trying to reproduce your work. You mentioned that you "compress the dataset and store in .pb". Are there some descriptions like commands or codes about how to use it?

**Comment by yunfanLu** [comment]
Hi, the pb description file can be found at https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/tools/1-CompressDataset/event_frame.proto#L1C1-L15C2.

You can refer to this guidance for using pb. It is simple: https://protobuf.dev/reference/python/python-generated/
