### ISSUE TITLE
About pre-training models

### ISSUE THREAD

**Issue by W-Shuoyan** [yunfanLu/INR-Event-VSR#11]
Hello! I'm also really interested in your pre-training models. Is it available now?

_Originally posted by @W-Shuoyan in https://github.com/yunfanLu/INR-Event-VSR/issues/9#issuecomment-2115512991_

**Comment by yunfanLu** [comment]
Hello, the model I retrained is in the shared network disk link. 
Sorry I didn't make that clear in the README.
