### ISSUE TITLE
Data set link failed.Can you provide a new link?

### ISSUE THREAD

**Issue by chahu-12** [yunfanLu/INR-Event-VSR#12]

**Comment by chahu-12** [comment]
Or is there an alternative data set to use?

**Comment by shen-aoyu** [comment]
can not download the datasets too

**Comment by yunfanLu** [comment]
The previous link is out of date, I have updated it. Thank you for your email reminder.

**Comment by chahu-12** [comment]
> The previous link is out of date, I have updated it. Thank you for your email reminder.

Thank you for your explanation.
I also have a question to ask.After downloaded the dataset, how to process the zip or avi files so that the code can run?

**Comment by yunfanLu** [comment]
Hi, the zip file contains the processed data. You just need to convert the pb (compressed) file into npy file to read it.  https://github.com/yunfanLu/INR-Event-VSR/blob/main/egvsr/datasets/alpx_vsr_dataset.py

avi is a visual file used to understand the content of the video.
