### ISSUE TITLE
Question about paper

### ISSUE THREAD

**Issue by Rtakaha** [yunfanLu/INR-Event-VSR#2]
Hi, I have 3 questions about the paper. 

These questions may become clear if I can read supp. material, but I cannot access to it yet. So it will be very helpful for me to understand your great work if you can answer here.

- What does HPB do exactly?
  - After first conv layer, F_0^f and F_0^e should be something like (H, W, N, C') and (H, W, M, C'), respectively. Is this correct?
  - In order to concatenate frame features and event features before Transformer block, temporal dimension of F_l^f should be same as F_l^e.
  -  I believe HPB does fix temporal dimension, so that the features can be properly concatenated and input to Transformer block. How does the HPB block fix the temporal dimension?

- What is the shape of the input for Transformer?
  - After the concatenation, the shape of the feature tensor should be (H, W, T', C').
  - How do you input this feature tensor to Transformer? Do you flatten first 3 dimension to make HxWxT tokens with feature dimension C'?

- What are the values of N and M for experiments?
  - I can guess from table 7 that N is either 5 or 3. Is this correct?
  - I couldn't find the value of M used for the experiments.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/22565574/235084579-8c3a84a2-ba23-489a-9146-c6121ee7411c.png">

Thank you in advance!

**Comment by yunfanLu** [comment]
Dear Rtakaha, thank you for your interest.

Regarding your first question:
For the HPB structure, please refer to the paper [1] for more details. Both the input and output of HPB have the shape $N C H W$.

Moving on to your second question:
The input shape of the transformer block is also $N C H W$. We have implemented the process outlined in the paper [1].

Lastly, in response to your last question:
We have set the value of N to be 3, 5, 7, and so on. Additionally, the value of M is fixed at 32.

I hope this clarification is helpful. Let me know if you have any further questions.


Reference:
[1] Transformer for Single Image Super-Resolution"(https://arxiv.org/pdf/2108.11084.pdf)

**Comment by Rtakaha** [comment]
Thank you! I have briefly checked the paper you mentioned, and I understand that:
- HPB block doesn't change the shape of feature tensor. So if NCHW is input, the output is also NCHW.
- Transformer is applied as below. When the input is NCHW, it will be unfolded to Nx(kkC)xHW, and input to Transformer.
  - <img width="917" alt="image" src="https://github.com/yunfanLu/INR-Event-VSR/assets/22565574/75a5ee20-6b8a-455f-a72b-f8750141be34">

I was unsure about the conv functions before HPB, but now I think I know how it works.
> we first employ two 1×1 convolutional layers to obtain the initial frame feature map and the event feature map with same dimension.

So 2 layers of convolution is applied to both frames and events, one is to fix the time-axis to T, and the other is to fix the feature-axis to C. After the conv layers, both frames and events has the shape of TCHW(NCHW), and there are no problems to concatenate those 2 features.

Please let me know if I am wrong. Thank you!
