### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by HebeiFast** [yunfanLu/INR-Event-VSR#4]
你的工作十分不错，论文中提到会公开数据并算在主要贡献内， 请问采集的数据什么时候公开

**Comment by yunfanLu** [comment]
你好，这个数据集有 300 多 GB，目前想办法正在上传一个合适的地方，完成后会尽快告诉你，感谢你的关注。

**Comment by yunfanLu** [comment]
https://github.com/yunfanLu/INR-Event-VSR/issues/5
