### ISSUE TITLE
Parameter meaning, TF branch code and random scale?

### ISSUE THREAD

**Issue by DachunKai** [yunfanLu/INR-Event-VSR#8]
Hi, thanks for your work. I have a few questions:

1.  Can you explain some parameter meanings, such as `is_include_bound `, `moments `, `event_channels `, `time_bins`, `inr_channel ` in [class RandomScaleSuperResolutionWithEvent](https://github.com/yunfanLu/INR-Event-VSR/blob/main/egvsr/models/rssrt/random_scale_super_resolution_with_event.py#L73-L100) . I'm very confused about  `moments `, `event_channels `, `time_bins` three parameters.

2. Where is the Temporal Filter (TF) Branch code in [RandomScaleSuperResolutionWithEvent](https://github.com/yunfanLu/INR-Event-VSR/blob/main/egvsr/models/rssrt/random_scale_super_resolution_with_event.py#L205-L230). From current code, I can get that a shallow and deep feature fusion, i.e. STF branch in the paper. Then I see the INR sampling code. There seems to miss TF branch code.

3. Why use `random_up_scale ` in [forward function](https://github.com/yunfanLu/INR-Event-VSR/blob/main/egvsr/models/rssrt/random_scale_super_resolution_with_event.py#L217). If you use `random_up_scale `, where is GT when training? How to get the desired scale sr result when inference? I'm so confused.

**Comment by DachunKai** [comment]
An interesting result! I ran the same code above three times, but got three different sr_img shapes. Can you help me understand the reason, or point out where I went wrong?

`sr_img.shape: torch.Size([1, 3, 140, 140])`
or
`sr_img.shape: torch.Size([1, 3, 230, 230])`
or
`sr_img.shape: torch.Size([1, 3, 128, 128])`

It seems very random.🥲

**Comment by yunfanLu** [comment]
Hello, thank you for your attention. I'm sorry for not logging in recently.

"moments" refers to dividing a period into how many segments, and "event_channels" indicates how many channels are used to represent each segment. In the specific function "event_stream_to_a_count_frame," the value of "event_channels" is 2, meaning that positive and negative triggers are represented using two channels each.

"time_bins" represents the INR of features after extracting events and images in the form of INR. I apologize if the name may be misleading, as it might be mistakenly associated with event representation.

If the TF branch is to be used, "event_residual_connection" needs to be set to true. In the code development, we didn't choose a clear name for TF, so it is written as "event_residual_connection." However, they essentially refer to the same thing.

Finally, "random_up_scale" is used because our method supports random upsampling. During training, a random number is set as the upsampling factor. The GT size is fixed, and resizing is performed when calculating the loss. Please refer to "RSSRLoss" for this part.

Thank you for your attention, and I hope my response is resolved. I'm sorry again for the delayed response.

**Comment by DachunKai** [comment]
Get it! Thanks.

**Comment by yunfanLu** [comment]
If there are no other issues, I will close this issue.

**Comment by yuanlinwang** [comment]
> The GT size is fixed, and resizing is performed when calculating the loss

@yunfanLu 您好，这是否表示loss是由预测的结果和resize的GT计算得到的，请问resize这个操作会对最终的结果造成影响吗？因为之前的论文大多是通过在线的方式生成输入和GT，即loss是由预测的结果和真实crop的HR图像计算得到的。
(resize这个操作是否是因为event data在线生成比较耗时？或是由于不存在任意比例的event和GT图像对）

以及您通过将
https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/models/rssrt/random_scale_super_resolution_with_event.py#L217
放在forward()中实现了同一个batch的输入数据具有同样的输出分辨率？

**Comment by yunfanLu** [comment]
> > The GT size is fixed, and resizing is performed when calculating the loss
> 
> @yunfanLu 您好，这是否表示loss是由预测的结果和resize的GT计算得到的，请问resize这个操作会对最终的结果造成影响吗？因为之前的论文大多是通过在线的方式生成输入和GT，即loss是由预测的结果和真实crop的HR图像计算得到的。 (resize这个操作是否是因为event data在线生成比较耗时？或是由于不存在任意比例的event和GT图像对）
> 
> 以及您通过将
> 
> https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/models/rssrt/random_scale_super_resolution_with_event.py#L217
> 
> 
> 放在forward()中实现了同一个batch的输入数据具有同样的输出分辨率？

您好，感谢对我们工作的关注。不好意思，今天才看到，没有及时回答。
我们的网络是支持任意分辨率的，所以在训练阶段是在这个区间里面取值，作为任意上采样倍数，来训练的。
1. 这是否表示loss是由预测的结果和resize的GT计算得到的？
 回答：是的。        [代码](https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/losses/image_loss.py#L63)](https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/losses/image_loss.py#L63)  代码这里写的。
2. 请问resize这个操作会对最终的结果造成影响吗？
 回答：resize 操作我们采用的是默认的函数，因为这里只涉及下采样。
3. 之前的论文大多是通过在线的方式生成输入和GT
 回答：我在实现的时候也是在线生成的。
4. resize这个操作是否是因为event data在线生成比较耗时？
 回答：resize 操作和 event 的在线生成是两个独立的。resize 是在网络后端操作的。
5. 放在forward()中实现了同一个batch的输入数据具有同样的输出分辨率？
 回答：是的。因为我们是任意尺度，所以是在 Forward 中实现的，这样实现出来是真正的随机。如果放到其他地方可能使得训练时无法用大的 batch size。

感谢您的关注，如果我还有没解释清楚的，请再提问。谢谢！

**Comment by yuanlinwang** [comment]
> > > The GT size is fixed, and resizing is performed when calculating the loss
> > 
> > 
> > @yunfanLu 您好，这是否表示loss是由预测的结果和resize的GT计算得到的，请问resize这个操作会对最终的结果造成影响吗？因为之前的论文大多是通过在线的方式生成输入和GT，即loss是由预测的结果和真实crop的HR图像计算得到的。 (resize这个操作是否是因为event data在线生成比较耗时？或是由于不存在任意比例的event和GT图像对）
> > 以及您通过将
> > https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/models/rssrt/random_scale_super_resolution_with_event.py#L217
> > 
> > 放在forward()中实现了同一个batch的输入数据具有同样的输出分辨率？
> 
> 您好，感谢对我们工作的关注。不好意思，今天才看到，没有及时回答。 我们的网络是支持任意分辨率的，所以在训练阶段是在这个区间里面取值，作为任意上采样倍数，来训练的。
> 
> 1. 这是否表示loss是由预测的结果和resize的GT计算得到的？
>    回答：是的。        [代码](https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/losses/image_loss.py#L63)](https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/losses/image_loss.py#L63
>    )  代码这里写的。
> 2. 请问resize这个操作会对最终的结果造成影响吗？
>    回答：resize 操作我们采用的是默认的函数，因为这里只涉及下采样。
> 3. 之前的论文大多是通过在线的方式生成输入和GT
>    回答：我在实现的时候也是在线生成的。
> 4. resize这个操作是否是因为event data在线生成比较耗时？
>    回答：resize 操作和 event 的在线生成是两个独立的。resize 是在网络后端操作的。
> 5. 放在forward()中实现了同一个batch的输入数据具有同样的输出分辨率？
>    回答：是的。因为我们是任意尺度，所以是在 Forward 中实现的，这样实现出来是真正的随机。如果放到其他地方可能使得训练时无法用大的 batch size。
> 
> 感谢您的关注，如果我还有没解释清楚的，请再提问。谢谢！

@yunfanLu 非常感谢您的详细回复，但我的一些问题有可能与您理解的稍微不一致，因此还有问题需要咨询：
1.”resize这个操作会对最终的结果造成影响吗？“
这个我的意思是 在计算loss时的GT不是真实的原图像中的GT，而是GT经resize后的图像，因此我担忧这里计算的loss是否会影响网络性能（因为resize可能或多或少会损失信息）
2.”之前的论文大多是通过在线的方式生成输入和GT“，这里我没太说清楚，我指的是LIIF及其之后的论文，会将GT通过bicubic下采样在训练过程中实时生成输入图像，而您论文训练时的event输入数据是在线从图像序列中生成的吗？（若是，麻烦请您引用一下相应的代码段）

**Comment by yunfanLu** [comment]
> > > > The GT size is fixed, and resizing is performed when calculating the loss
> > > 
> > > 
> > > @yunfanLu 您好，这是否表示loss是由预测的结果和resize的GT计算得到的，请问resize这个操作会对最终的结果造成影响吗？因为之前的论文大多是通过在线的方式生成输入和GT，即loss是由预测的结果和真实crop的HR图像计算得到的。 (resize这个操作是否是因为event data在线生成比较耗时？或是由于不存在任意比例的event和GT图像对）
> > > 以及您通过将
> > > https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/models/rssrt/random_scale_super_resolution_with_event.py#L217
> > > 
> > > 放在forward()中实现了同一个batch的输入数据具有同样的输出分辨率？
> > 
> > 
> > 您好，感谢对我们工作的关注。不好意思，今天才看到，没有及时回答。 我们的网络是支持任意分辨率的，所以在训练阶段是在这个区间里面取值，作为任意上采样倍数，来训练的。
> > 
> > 1. 这是否表示loss是由预测的结果和resize的GT计算得到的？
> >    回答：是的。        [代码](https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/losses/image_loss.py#L63)](https://github.com/yunfanLu/INR-Event-VSR/blob/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/losses/image_loss.py#L63
> >    
> >    )  代码这里写的。
> > 2. 请问resize这个操作会对最终的结果造成影响吗？
> >    回答：resize 操作我们采用的是默认的函数，因为这里只涉及下采样。
> > 3. 之前的论文大多是通过在线的方式生成输入和GT
> >    回答：我在实现的时候也是在线生成的。
> > 4. resize这个操作是否是因为event data在线生成比较耗时？
> >    回答：resize 操作和 event 的在线生成是两个独立的。resize 是在网络后端操作的。
> > 5. 放在forward()中实现了同一个batch的输入数据具有同样的输出分辨率？
> >    回答：是的。因为我们是任意尺度，所以是在 Forward 中实现的，这样实现出来是真正的随机。如果放到其他地方可能使得训练时无法用大的 batch size。
> > 
> > 感谢您的关注，如果我还有没解释清楚的，请再提问。谢谢！
> 
> @yunfanLu 非常感谢您的详细回复，但我的一些问题有可能与您理解的稍微不一致，因此还有问题需要咨询： 1.”resize这个操作会对最终的结果造成影响吗？“ 这个我的意思是 在计算loss时的GT不是真实的原图像中的GT，而是GT经resize后的图像，因此我担忧这里计算的loss是否会影响网络性能（因为resize可能或多或少会损失信息） 2.”之前的论文大多是通过在线的方式生成输入和GT“，这里我没太说清楚，我指的是LIIF及其之后的论文，会将GT通过bicubic下采样在训练过程中实时生成输入图像，而您论文训练时的event输入数据是在线从图像序列中生成的吗？（若是，麻烦请您引用一下相应的代码段）

问题1：  在计算loss时的GT不是真实的原图像中的GT，而是GT经resize后的图像，因此我担忧这里计算的loss是否会影响网络性能（因为resize可能或多或少会损失信息）
回答：你好，我们测试的时候是直接以固定倍数测试的。单纯从测试的时候看，resize 应该是没有影响的。因为这里是下采样，和LIIF里的方式其实是一样的。一个简单的理解是，下采样后GT的信息量还是多于输入低分辨率的。就比如说，一种方式是固定GT的分辨率，每次调整输入的分辨率，这样也肯导致输入中的尺度和真实输入是不一致。这样也可能导致网络性能的差异。
问题2：训练时的event输入数据是在线从图像序列中生成的吗？
回答：event 数据是相机采集的，不是在线图像序列生成的。您可以看下 dataset 部分。

**Comment by yunfanLu** [comment]
您好，event 数据是相机采集得到的。我们在读取数据时，event 和 rgb 都是从本地 load 上来的。具体的代码在这里。

https://github.com/yunfanLu/INR-Event-VSR/blame/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/datasets/color_event_dataset.py#L185C28-L185C28

**Comment by yuanlinwang** [comment]
> 您好，event 数据是相机采集得到的。我们在读取数据时，event 和 rgb 都是从本地 load 上来的。具体的代码在这里。
> 
> https://github.com/yunfanLu/INR-Event-VSR/blame/d384ab3b67523fdefa65331a22b5a913cd300847/egvsr/datasets/color_event_dataset.py#L185C28-L185C28

非常感谢您的回复，我的疑惑已经都得到了解答，谢谢！
