### ISSUE TITLE
pre-trained models 

### ISSUE THREAD

**Issue by Zehaoc** [yunfanLu/INR-Event-VSR#9]
Hi, Would it be possible for you to share the pre-trained models from your paper?

**Comment by yunfanLu** [comment]
I am sorry for not being able to respond to your message sooner. The models in question were hosted on the machines of a previous funding partner, with whom I have not been associated for quite a long time now. To resolve this, I will retrain the models. Once the retraining process is complete, I will ensure to share the updated model with you. I appreciate your patience.

**Comment by W-Shuoyan** [comment]
Hello! I'm also really interested in your pre-training models. Is it available now?
